"""Add status field to keyword series and protagonist

Revision ID: 0b21610de1bb
Revises: 4dcac9e0068a
Create Date: 2026-03-08 21:46:40.476310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b21610de1bb'
down_revision = '4dcac9e0068a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('protagonist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('protagonist', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
