"""Add background_image to theme

Revision ID: 1216bdd6e093
Revises: 56a86f2c5358
Create Date: 2026-02-08 01:06:21.911805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1216bdd6e093'
down_revision = '56a86f2c5358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_card', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_community_card_display_order'))

    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key('fk_post_series', 'series', ['series_id'], ['id'])

    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.String(length=255), nullable=True))
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('icon_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'emoji'"),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('background_image')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_series', type_='foreignkey')
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('community_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_community_card_display_order'), ['display_order'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
