"""Add card_image to Theme

Revision ID: 54d1f05b3f53
Revises: 9f7461ef9231
Create Date: 2026-02-10 15:17:41.047229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d1f05b3f53'
down_revision = '9f7461ef9231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theme', schema=None) as batch_op:
        batch_op.drop_column('card_image')

    # ### end Alembic commands ###
