"""Add CMSUser model

Revision ID: 5561f3658ded
Revises: c388eb5094c5
Create Date: 2026-03-08 19:03:15.883435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5561f3658ded'
down_revision = 'c388eb5094c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('community_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title_html', sa.TEXT(), nullable=False),
    sa.Column('body_html', sa.TEXT(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cms_user')
    # ### end Alembic commands ###
