"""Add Series model and post series relationship

Revision ID: 56a86f2c5358
Revises: ed0ee6ed1caa
Create Date: 2025-10-20 18:57:14.927326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a86f2c5358'
down_revision = 'ed0ee6ed1caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('series_order', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_post_series_id', 'series', ['series_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_series_id', type_='foreignkey')
        batch_op.drop_column('series_order')
        batch_op.drop_column('series_id')

    op.drop_table('series')
    # ### end Alembic commands ###
