"""Update Subscriber model with IP and Country

Revision ID: c388eb5094c5
Revises: 2d6cc3133722
Create Date: 2026-03-08 15:49:47.823620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c388eb5094c5'
down_revision = '2d6cc3133722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
